export const BRANDS = [
  'Milwaukee',
  'DeWalt',
  'Makita',
  'Bosch',
  'Ridgid',
  'Ryobi',
  'Hilti',
  'Klein',
  'Diablo',
  'Other',
];
export const CATEGORIES = [
  'Drill',
  'Impact Driver',
  'Hammer Drill',
  'Impact Wrench',
  'Grinder',
  'Circular Saw',
  'Reciprocating Saw',
  'Multi-Tool',
  'Router',
  'Nailer',
  'Compressor',
  'Vacuum',
  'Battery',
  'Charger',
  'Combo Kit',
  'Hand Tool',
  'Accessory',
  'Other',
];
export const PLATFORMS = [
  'M12',
  'M18',
  'MX FUEL',
  '20V MAX',
  'FLEXVOLT',
  '18V LXT',
  'Corded',
  'N/A',
];
export const CONDITIONS = [
  'New',
  'New Open Box',
  'Like New',
  'Excellent Used',
  'Good Used',
  'Fair Used',
  'For Parts / Repair',
];
export const LOCATIONS = [
  'Garage Shelf A',
  'Garage Shelf B',
  'Storage Bin 1',
  'Storage Bin 2',
  'Office',
  'Vehicle',
  'Warehouse',
  'Other',
];
